{"errorMessage": "An error occurred (AccessDeniedException) when calling the GetSecretValue operation: User: arn:aws:sts::975049905873:assumed-role/hue-lighting-stack-HueLightingFunctionRole-0ePS56TMlBfA/hue-lighting-stack-HueLightingFunction-x3lqLgkbo33h is not authorized to perform: secretsmanager:GetSecretValue on resource: hue-api/oauth because no identity-based policy allows the secretsmanager:GetSecretValue action", "errorType": "ClientError", "requestId": "817ebb06-3a16-4b5e-b400-bc596f972380", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 60, in lambda_handler\n    client_id, client_secret = get_oauth_secrets()\n", "  File \"/var/task/lambda_function.py\", line 32, in get_oauth_secrets\n    raise e\n", "  File \"/var/task/lambda_function.py\", line 21, in get_oauth_secrets\n    secret_response = client.get_secret_value(SecretId='hue-api/oauth')\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}